// -------------------------------------------------------------
// 
// File Name: G:\AI\IIT BHU\codegen\hdldct\hdlsrc\hdldct_FixPt.v
// Created: 2016-06-28 12:58:38
// 
// Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// d                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: hdldct_FixPt
// Source Path: hdldct_FixPt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module hdldct_FixPt
          (
           clk,
           reset,
           clk_enable,
           i,
           j,
           m,
           n,
           ce_out,
           d
          );


  input   clk;
  input   reset;
  input   clk_enable;
  input   [2:0] i;  // ufix3
  input   [2:0] j;  // ufix3
  input   [7:0] m;  // ufix8
  input   [2:0] n;  // ufix3
  output  ce_out;
  output  signed [7:0] d;  // sfix8


  wire enb;
  reg signed [7:0] d_1;  // sfix8
  reg signed [15:0] hdldct_FixPt_FI_SIN_COS_LUT_1 [0:255];  // sfix16 [256]
  reg signed [15:0] hdldct_FixPt_FI_SIN_COS_LUT_2 [0:255];  // sfix16_En15 [256]
  reg [13:0] hdldct_FixPt_t3_1;  // ufix14_En10
  reg [15:0] hdldct_FixPt_inputValue_1;  // ufix16_En10
  reg [31:0] hdldct_FixPt_iA_1;  // uint32
  reg [15:0] hdldct_FixPt_inputValue_0_1;  // ufix16_En10
  reg [31:0] hdldct_FixPt_iA_0_1;  // uint32
  reg [15:0] hdldct_FixPt_tmp_3;  // ufix16_En13
  reg [15:0] hdldct_FixPt_fullScaleIndex_1;  // ufix16
  reg [7:0] hdldct_FixPt_idxLUTLoZero_1;  // ufix8
  reg signed [15:0] hdldct_FixPt_idxLUTLoAddr_1;  // int16
  reg signed [15:0] hdldct_FixPt_temp_1;  // sfix16_En15
  reg signed [39:0] hdldct_FixPt_c_1;  // sfix40_En30
  reg signed [10:0] hdldct_FixPt_tmp_0_1;  // sfix11
  reg [4:0] hdldct_FixPt_c1_1;  // ufix5_En2
  reg [2:0] hdldct_FixPt_ytemp_1;  // ufix3_En1
  reg [2:0] hdldct_FixPt_y_1;  // ufix3_En1
  reg signed [31:0] hdldct_FixPt_i_1;  // int32
  reg [2:0] hdldct_FixPt_ytempPlusLsb_1;  // ufix3_En1
  reg [15:0] hdldct_FixPt_tmp_1_1;  // ufix16_En13
  reg [15:0] hdldct_FixPt_fullScaleIndex_0_1;  // ufix16
  reg [7:0] hdldct_FixPt_idxLUTLoZero_0_1;  // ufix8
  reg signed [15:0] hdldct_FixPt_idxLUTLoAddr_0_1;  // int16
  reg signed [15:0] hdldct_FixPt_temp_0_1;  // sfix16_En15
  reg signed [29:0] hdldct_FixPt_c_0_1;  // sfix30_En19
  reg signed [11:0] hdldct_FixPt_tmp_2_1;  // sfix12
  reg signed [31:0] hdldct_FixPt_t_0_1;  // int32
  reg signed [31:0] hdldct_FixPt_t_1_1;  // int32
  reg signed [15:0] hdldct_FixPt_t_2_1 [0:255];  // sfix16_En15 [256]
  reg [10:0] hdldct_FixPt_div_temp_3;  // ufix11_En5
  reg [3:0] hdldct_FixPt_div_temp_0_1;  // ufix4_En2
  reg [31:0] hdldct_FixPt_div_temp_1_1;  // ufix32
  reg [31:0] hdldct_FixPt_div_temp_2_1;  // ufix32
  reg [4:0] hdldct_FixPt_cast_39;  // ufix5
  reg [4:0] hdldct_FixPt_sub_cast_14;  // ufix5
  reg signed [6:0] hdldct_FixPt_sub_temp_9;  // sfix7
  reg [5:0] hdldct_FixPt_cast_0_1;  // ufix6
  reg [10:0] hdldct_FixPt_cast_1_1;  // ufix11_En5
  reg [4:0] hdldct_FixPt_cast_2_1;  // ufix5
  reg [3:0] hdldct_FixPt_sub_temp_0_1;  // ufix4
  reg [7:0] hdldct_FixPt_mul_temp_18;  // ufix8_En2
  reg [13:0] hdldct_FixPt_cast_3_1;  // ufix14_En10
  reg [13:0] hdldct_FixPt_cast_4_1;  // ufix14_En14
  reg [27:0] hdldct_FixPt_mul_temp_0_1;  // ufix28_En24
  reg [31:0] hdldct_FixPt_cast_5_1;  // ufix32_En26
  reg [31:0] hdldct_FixPt_cast_6_1;  // ufix32_En26
  reg [31:0] hdldct_FixPt_sub_cast_0_1;  // uint32
  reg [31:0] hdldct_FixPt_sub_temp_1_1;  // ufix32_En26
  reg [15:0] hdldct_FixPt_cast_7_1;  // uint16
  reg [47:0] hdldct_FixPt_mul_temp_1_1;  // ufix48_En31
  reg [31:0] hdldct_FixPt_cast_8_1;  // ufix32_En16
  reg [3:0] hdldct_FixPt_add_cast_12;  // ufix4_En1
  reg [3:0] hdldct_FixPt_add_temp_8;  // ufix4_En1
  reg [7:0] hdldct_FixPt_cast_9_1 [0:2];  // uint8 [3]
  reg [2:0] hdldct_FixPt_sll_temp_1 [0:2];  // ufix3_En1 [3]
  reg signed [8:0] hdldct_FixPt_cast_10_1;  // sfix9_En8
  reg signed [15:0] hdldct_FixPt_add_temp_0_1;  // sfix16
  reg signed [31:0] hdldct_FixPt_sub_cast_1_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_sub_cast_2_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_sub_temp_2_1;  // sfix32_En30
  reg signed [40:0] hdldct_FixPt_mul_temp_2_1;  // sfix41_En38
  reg signed [31:0] hdldct_FixPt_cast_11_1;  // sfix32_En30
  reg [5:0] hdldct_FixPt_mul_temp_3_1;  // ufix6_En2
  reg signed [6:0] hdldct_FixPt_sub_cast_3_1;  // sfix7_En2
  reg signed [6:0] hdldct_FixPt_sub_cast_4_1;  // sfix7_En2
  reg signed [6:0] hdldct_FixPt_sub_temp_3_1;  // sfix7_En2
  reg [5:0] hdldct_FixPt_cast_12_1;  // ufix6_En2
  reg signed [6:0] hdldct_FixPt_sub_cast_5_1;  // sfix7_En2
  reg [5:0] hdldct_FixPt_mul_temp_4_1;  // ufix6_En2
  reg signed [6:0] hdldct_FixPt_sub_cast_6_1;  // sfix7_En2
  reg signed [6:0] hdldct_FixPt_sub_temp_4_1;  // sfix7_En2
  reg [5:0] hdldct_FixPt_cast_13_1;  // ufix6_En2
  reg [5:0] hdldct_FixPt_mul_temp_5_1 [0:2];  // ufix6_En2 [3]
  reg [5:0] hdldct_FixPt_cast_14_1 [0:2];  // ufix6_En2 [3]
  reg signed [31:0] hdldct_FixPt_add_cast_0_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_cast_1_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_temp_1_1;  // sfix32_En30
  reg signed [15:0] hdldct_FixPt_cast_15_1;  // sfix16_En15
  reg signed [31:0] hdldct_FixPt_mul_temp_6_1;  // sfix32_En30
  reg signed [8:0] hdldct_FixPt_cast_16_1;  // sfix9
  reg signed [40:0] hdldct_FixPt_mul_temp_7_1;  // sfix41_En30
  reg signed [31:0] hdldct_FixPt_add_cast_2_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_cast_3_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_temp_2_1;  // sfix32_En30
  reg signed [15:0] hdldct_FixPt_cast_17_1;  // sfix16_En15
  reg signed [31:0] hdldct_FixPt_mul_temp_8_1;  // sfix32_En30
  reg signed [8:0] hdldct_FixPt_cast_18_1;  // sfix9
  reg signed [40:0] hdldct_FixPt_mul_temp_9_1;  // sfix41_En30
  reg signed [39:0] hdldct_FixPt_cast_19_1;  // sfix40_En30
  reg signed [11:0] hdldct_FixPt_add_cast_4_1;  // sfix12_En1
  reg signed [12:0] hdldct_FixPt_add_cast_5_1;  // sfix13_En1
  reg signed [12:0] hdldct_FixPt_add_temp_3_1;  // sfix13_En1
  reg signed [11:0] hdldct_FixPt_cast_20_1;  // sfix12_En1
  reg signed [11:0] hdldct_FixPt_sub_cast_7_1;  // sfix12_En1
  reg signed [12:0] hdldct_FixPt_sub_cast_8_1;  // sfix13_En1
  reg signed [12:0] hdldct_FixPt_sub_temp_5_1;  // sfix13_En1
  reg signed [11:0] hdldct_FixPt_cast_21_1;  // sfix12_En1
  reg signed [11:0] hdldct_FixPt_cast_22_1;  // sfix12
  reg [31:0] hdldct_FixPt_sub_cast_9_1;  // uint32
  reg [31:0] hdldct_FixPt_sub_temp_6_1;  // ufix32_En26
  reg [15:0] hdldct_FixPt_cast_23_1;  // uint16
  reg [47:0] hdldct_FixPt_mul_temp_10_1;  // ufix48_En31
  reg [31:0] hdldct_FixPt_cast_24_1;  // ufix32_En16
  reg signed [8:0] hdldct_FixPt_cast_25_1;  // sfix9_En8
  reg signed [15:0] hdldct_FixPt_add_temp_4_1;  // sfix16
  reg signed [31:0] hdldct_FixPt_sub_cast_10_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_sub_cast_11_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_sub_temp_7_1;  // sfix32_En30
  reg signed [40:0] hdldct_FixPt_mul_temp_11_1;  // sfix41_En38
  reg signed [31:0] hdldct_FixPt_cast_26_1;  // sfix32_En30
  reg [5:0] hdldct_FixPt_mul_temp_12_1;  // ufix6_En4
  reg signed [6:0] hdldct_FixPt_cast_27_1;  // sfix7_En4
  reg signed [31:0] hdldct_FixPt_add_cast_6_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_cast_7_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_temp_5_1;  // sfix32_En30
  reg signed [15:0] hdldct_FixPt_cast_28_1;  // sfix16_En15
  reg signed [22:0] hdldct_FixPt_mul_temp_13_1;  // sfix23_En19
  reg signed [21:0] hdldct_FixPt_cast_29_1;  // sfix22_En19
  reg signed [8:0] hdldct_FixPt_cast_30_1;  // sfix9
  reg signed [30:0] hdldct_FixPt_mul_temp_14_1;  // sfix31_En19
  reg [5:0] hdldct_FixPt_mul_temp_15_1;  // ufix6_En4
  reg signed [6:0] hdldct_FixPt_cast_31_1;  // sfix7_En4
  reg signed [31:0] hdldct_FixPt_add_cast_8_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_cast_9_1;  // sfix32_En30
  reg signed [31:0] hdldct_FixPt_add_temp_6_1;  // sfix32_En30
  reg signed [15:0] hdldct_FixPt_cast_32_1;  // sfix16_En15
  reg signed [22:0] hdldct_FixPt_mul_temp_16_1;  // sfix23_En19
  reg signed [21:0] hdldct_FixPt_cast_33_1;  // sfix22_En19
  reg signed [8:0] hdldct_FixPt_cast_34_1;  // sfix9
  reg signed [30:0] hdldct_FixPt_mul_temp_17_1;  // sfix31_En19
  reg signed [29:0] hdldct_FixPt_cast_35_1;  // sfix30_En19
  reg signed [12:0] hdldct_FixPt_add_cast_10_1;  // sfix13_En1
  reg signed [13:0] hdldct_FixPt_add_cast_11_1;  // sfix14_En1
  reg signed [13:0] hdldct_FixPt_add_temp_7_1;  // sfix14_En1
  reg signed [12:0] hdldct_FixPt_cast_36_1;  // sfix13_En1
  reg signed [12:0] hdldct_FixPt_sub_cast_12_1;  // sfix13_En1
  reg signed [13:0] hdldct_FixPt_sub_cast_13_1;  // sfix14_En1
  reg signed [13:0] hdldct_FixPt_sub_temp_8_1;  // sfix14_En1
  reg signed [12:0] hdldct_FixPt_cast_37_1;  // sfix13_En1
  reg signed [12:0] hdldct_FixPt_cast_38_1;  // sfix13


  assign enb = clk_enable;

  always @(i, j, m, n) begin
    hdldct_FixPt_t_2_1[0] = 16'sb0111111111111111;
    hdldct_FixPt_t_2_1[1] = 16'sb0111111111110110;
    hdldct_FixPt_t_2_1[2] = 16'sb0111111111011001;
    hdldct_FixPt_t_2_1[3] = 16'sb0111111110100111;
    hdldct_FixPt_t_2_1[4] = 16'sb0111111101100010;
    hdldct_FixPt_t_2_1[5] = 16'sb0111111100001010;
    hdldct_FixPt_t_2_1[6] = 16'sb0111111010011101;
    hdldct_FixPt_t_2_1[7] = 16'sb0111111000011110;
    hdldct_FixPt_t_2_1[8] = 16'sb0111110110001010;
    hdldct_FixPt_t_2_1[9] = 16'sb0111110011100100;
    hdldct_FixPt_t_2_1[10] = 16'sb0111110000101010;
    hdldct_FixPt_t_2_1[11] = 16'sb0111101101011101;
    hdldct_FixPt_t_2_1[12] = 16'sb0111101001111101;
    hdldct_FixPt_t_2_1[13] = 16'sb0111100110001010;
    hdldct_FixPt_t_2_1[14] = 16'sb0111100010000101;
    hdldct_FixPt_t_2_1[15] = 16'sb0111011101101100;
    hdldct_FixPt_t_2_1[16] = 16'sb0111011001000010;
    hdldct_FixPt_t_2_1[17] = 16'sb0111010100000101;
    hdldct_FixPt_t_2_1[18] = 16'sb0111001110110110;
    hdldct_FixPt_t_2_1[19] = 16'sb0111001001010101;
    hdldct_FixPt_t_2_1[20] = 16'sb0111000011100011;
    hdldct_FixPt_t_2_1[21] = 16'sb0110111101011111;
    hdldct_FixPt_t_2_1[22] = 16'sb0110110111001010;
    hdldct_FixPt_t_2_1[23] = 16'sb0110110000100100;
    hdldct_FixPt_t_2_1[24] = 16'sb0110101001101110;
    hdldct_FixPt_t_2_1[25] = 16'sb0110100010100111;
    hdldct_FixPt_t_2_1[26] = 16'sb0110011011010000;
    hdldct_FixPt_t_2_1[27] = 16'sb0110010011101001;
    hdldct_FixPt_t_2_1[28] = 16'sb0110001011110010;
    hdldct_FixPt_t_2_1[29] = 16'sb0110000011101100;
    hdldct_FixPt_t_2_1[30] = 16'sb0101111011010111;
    hdldct_FixPt_t_2_1[31] = 16'sb0101110010110100;
    hdldct_FixPt_t_2_1[32] = 16'sb0101101010000010;
    hdldct_FixPt_t_2_1[33] = 16'sb0101100001000011;
    hdldct_FixPt_t_2_1[34] = 16'sb0101010111110110;
    hdldct_FixPt_t_2_1[35] = 16'sb0101001110011011;
    hdldct_FixPt_t_2_1[36] = 16'sb0101000100110100;
    hdldct_FixPt_t_2_1[37] = 16'sb0100111011000000;
    hdldct_FixPt_t_2_1[38] = 16'sb0100110001000000;
    hdldct_FixPt_t_2_1[39] = 16'sb0100100110110100;
    hdldct_FixPt_t_2_1[40] = 16'sb0100011100011101;
    hdldct_FixPt_t_2_1[41] = 16'sb0100010001111011;
    hdldct_FixPt_t_2_1[42] = 16'sb0100000111001110;
    hdldct_FixPt_t_2_1[43] = 16'sb0011111100010111;
    hdldct_FixPt_t_2_1[44] = 16'sb0011110001010111;
    hdldct_FixPt_t_2_1[45] = 16'sb0011100110001101;
    hdldct_FixPt_t_2_1[46] = 16'sb0011011010111010;
    hdldct_FixPt_t_2_1[47] = 16'sb0011001111011111;
    hdldct_FixPt_t_2_1[48] = 16'sb0011000011111100;
    hdldct_FixPt_t_2_1[49] = 16'sb0010111000010001;
    hdldct_FixPt_t_2_1[50] = 16'sb0010101100011111;
    hdldct_FixPt_t_2_1[51] = 16'sb0010100000100111;
    hdldct_FixPt_t_2_1[52] = 16'sb0010010100101000;
    hdldct_FixPt_t_2_1[53] = 16'sb0010001000100100;
    hdldct_FixPt_t_2_1[54] = 16'sb0001111100011010;
    hdldct_FixPt_t_2_1[55] = 16'sb0001110000001100;
    hdldct_FixPt_t_2_1[56] = 16'sb0001100011111001;
    hdldct_FixPt_t_2_1[57] = 16'sb0001010111100010;
    hdldct_FixPt_t_2_1[58] = 16'sb0001001011001000;
    hdldct_FixPt_t_2_1[59] = 16'sb0000111110101011;
    hdldct_FixPt_t_2_1[60] = 16'sb0000110010001100;
    hdldct_FixPt_t_2_1[61] = 16'sb0000100101101011;
    hdldct_FixPt_t_2_1[62] = 16'sb0000011001001000;
    hdldct_FixPt_t_2_1[63] = 16'sb0000001100100100;
    hdldct_FixPt_t_2_1[64] = 16'sb0000000000000000;
    hdldct_FixPt_t_2_1[65] = 16'sb1111110011011100;
    hdldct_FixPt_t_2_1[66] = 16'sb1111100110111000;
    hdldct_FixPt_t_2_1[67] = 16'sb1111011010010101;
    hdldct_FixPt_t_2_1[68] = 16'sb1111001101110100;
    hdldct_FixPt_t_2_1[69] = 16'sb1111000001010101;
    hdldct_FixPt_t_2_1[70] = 16'sb1110110100111000;
    hdldct_FixPt_t_2_1[71] = 16'sb1110101000011110;
    hdldct_FixPt_t_2_1[72] = 16'sb1110011100000111;
    hdldct_FixPt_t_2_1[73] = 16'sb1110001111110100;
    hdldct_FixPt_t_2_1[74] = 16'sb1110000011100110;
    hdldct_FixPt_t_2_1[75] = 16'sb1101110111011100;
    hdldct_FixPt_t_2_1[76] = 16'sb1101101011011000;
    hdldct_FixPt_t_2_1[77] = 16'sb1101011111011001;
    hdldct_FixPt_t_2_1[78] = 16'sb1101010011100001;
    hdldct_FixPt_t_2_1[79] = 16'sb1101000111101111;
    hdldct_FixPt_t_2_1[80] = 16'sb1100111100000100;
    hdldct_FixPt_t_2_1[81] = 16'sb1100110000100001;
    hdldct_FixPt_t_2_1[82] = 16'sb1100100101000110;
    hdldct_FixPt_t_2_1[83] = 16'sb1100011001110011;
    hdldct_FixPt_t_2_1[84] = 16'sb1100001110101001;
    hdldct_FixPt_t_2_1[85] = 16'sb1100000011101001;
    hdldct_FixPt_t_2_1[86] = 16'sb1011111000110010;
    hdldct_FixPt_t_2_1[87] = 16'sb1011101110000101;
    hdldct_FixPt_t_2_1[88] = 16'sb1011100011100011;
    hdldct_FixPt_t_2_1[89] = 16'sb1011011001001100;
    hdldct_FixPt_t_2_1[90] = 16'sb1011001111000000;
    hdldct_FixPt_t_2_1[91] = 16'sb1011000101000000;
    hdldct_FixPt_t_2_1[92] = 16'sb1010111011001100;
    hdldct_FixPt_t_2_1[93] = 16'sb1010110001100101;
    hdldct_FixPt_t_2_1[94] = 16'sb1010101000001010;
    hdldct_FixPt_t_2_1[95] = 16'sb1010011110111101;
    hdldct_FixPt_t_2_1[96] = 16'sb1010010101111110;
    hdldct_FixPt_t_2_1[97] = 16'sb1010001101001100;
    hdldct_FixPt_t_2_1[98] = 16'sb1010000100101001;
    hdldct_FixPt_t_2_1[99] = 16'sb1001111100010100;
    hdldct_FixPt_t_2_1[100] = 16'sb1001110100001110;
    hdldct_FixPt_t_2_1[101] = 16'sb1001101100010111;
    hdldct_FixPt_t_2_1[102] = 16'sb1001100100110000;
    hdldct_FixPt_t_2_1[103] = 16'sb1001011101011001;
    hdldct_FixPt_t_2_1[104] = 16'sb1001010110010010;
    hdldct_FixPt_t_2_1[105] = 16'sb1001001111011100;
    hdldct_FixPt_t_2_1[106] = 16'sb1001001000110110;
    hdldct_FixPt_t_2_1[107] = 16'sb1001000010100001;
    hdldct_FixPt_t_2_1[108] = 16'sb1000111100011101;
    hdldct_FixPt_t_2_1[109] = 16'sb1000110110101011;
    hdldct_FixPt_t_2_1[110] = 16'sb1000110001001010;
    hdldct_FixPt_t_2_1[111] = 16'sb1000101011111011;
    hdldct_FixPt_t_2_1[112] = 16'sb1000100110111110;
    hdldct_FixPt_t_2_1[113] = 16'sb1000100010010100;
    hdldct_FixPt_t_2_1[114] = 16'sb1000011101111011;
    hdldct_FixPt_t_2_1[115] = 16'sb1000011001110110;
    hdldct_FixPt_t_2_1[116] = 16'sb1000010110000011;
    hdldct_FixPt_t_2_1[117] = 16'sb1000010010100011;
    hdldct_FixPt_t_2_1[118] = 16'sb1000001111010110;
    hdldct_FixPt_t_2_1[119] = 16'sb1000001100011100;
    hdldct_FixPt_t_2_1[120] = 16'sb1000001001110110;
    hdldct_FixPt_t_2_1[121] = 16'sb1000000111100010;
    hdldct_FixPt_t_2_1[122] = 16'sb1000000101100011;
    hdldct_FixPt_t_2_1[123] = 16'sb1000000011110110;
    hdldct_FixPt_t_2_1[124] = 16'sb1000000010011110;
    hdldct_FixPt_t_2_1[125] = 16'sb1000000001011001;
    hdldct_FixPt_t_2_1[126] = 16'sb1000000000100111;
    hdldct_FixPt_t_2_1[127] = 16'sb1000000000001010;
    hdldct_FixPt_t_2_1[128] = 16'sb1000000000000001;
    hdldct_FixPt_t_2_1[129] = 16'sb1000000000001010;
    hdldct_FixPt_t_2_1[130] = 16'sb1000000000100111;
    hdldct_FixPt_t_2_1[131] = 16'sb1000000001011001;
    hdldct_FixPt_t_2_1[132] = 16'sb1000000010011110;
    hdldct_FixPt_t_2_1[133] = 16'sb1000000011110110;
    hdldct_FixPt_t_2_1[134] = 16'sb1000000101100011;
    hdldct_FixPt_t_2_1[135] = 16'sb1000000111100010;
    hdldct_FixPt_t_2_1[136] = 16'sb1000001001110110;
    hdldct_FixPt_t_2_1[137] = 16'sb1000001100011100;
    hdldct_FixPt_t_2_1[138] = 16'sb1000001111010110;
    hdldct_FixPt_t_2_1[139] = 16'sb1000010010100011;
    hdldct_FixPt_t_2_1[140] = 16'sb1000010110000011;
    hdldct_FixPt_t_2_1[141] = 16'sb1000011001110110;
    hdldct_FixPt_t_2_1[142] = 16'sb1000011101111011;
    hdldct_FixPt_t_2_1[143] = 16'sb1000100010010100;
    hdldct_FixPt_t_2_1[144] = 16'sb1000100110111110;
    hdldct_FixPt_t_2_1[145] = 16'sb1000101011111011;
    hdldct_FixPt_t_2_1[146] = 16'sb1000110001001010;
    hdldct_FixPt_t_2_1[147] = 16'sb1000110110101011;
    hdldct_FixPt_t_2_1[148] = 16'sb1000111100011101;
    hdldct_FixPt_t_2_1[149] = 16'sb1001000010100001;
    hdldct_FixPt_t_2_1[150] = 16'sb1001001000110110;
    hdldct_FixPt_t_2_1[151] = 16'sb1001001111011100;
    hdldct_FixPt_t_2_1[152] = 16'sb1001010110010010;
    hdldct_FixPt_t_2_1[153] = 16'sb1001011101011001;
    hdldct_FixPt_t_2_1[154] = 16'sb1001100100110000;
    hdldct_FixPt_t_2_1[155] = 16'sb1001101100010111;
    hdldct_FixPt_t_2_1[156] = 16'sb1001110100001110;
    hdldct_FixPt_t_2_1[157] = 16'sb1001111100010100;
    hdldct_FixPt_t_2_1[158] = 16'sb1010000100101001;
    hdldct_FixPt_t_2_1[159] = 16'sb1010001101001100;
    hdldct_FixPt_t_2_1[160] = 16'sb1010010101111110;
    hdldct_FixPt_t_2_1[161] = 16'sb1010011110111101;
    hdldct_FixPt_t_2_1[162] = 16'sb1010101000001010;
    hdldct_FixPt_t_2_1[163] = 16'sb1010110001100101;
    hdldct_FixPt_t_2_1[164] = 16'sb1010111011001100;
    hdldct_FixPt_t_2_1[165] = 16'sb1011000101000000;
    hdldct_FixPt_t_2_1[166] = 16'sb1011001111000000;
    hdldct_FixPt_t_2_1[167] = 16'sb1011011001001100;
    hdldct_FixPt_t_2_1[168] = 16'sb1011100011100011;
    hdldct_FixPt_t_2_1[169] = 16'sb1011101110000101;
    hdldct_FixPt_t_2_1[170] = 16'sb1011111000110010;
    hdldct_FixPt_t_2_1[171] = 16'sb1100000011101001;
    hdldct_FixPt_t_2_1[172] = 16'sb1100001110101001;
    hdldct_FixPt_t_2_1[173] = 16'sb1100011001110011;
    hdldct_FixPt_t_2_1[174] = 16'sb1100100101000110;
    hdldct_FixPt_t_2_1[175] = 16'sb1100110000100001;
    hdldct_FixPt_t_2_1[176] = 16'sb1100111100000100;
    hdldct_FixPt_t_2_1[177] = 16'sb1101000111101111;
    hdldct_FixPt_t_2_1[178] = 16'sb1101010011100001;
    hdldct_FixPt_t_2_1[179] = 16'sb1101011111011001;
    hdldct_FixPt_t_2_1[180] = 16'sb1101101011011000;
    hdldct_FixPt_t_2_1[181] = 16'sb1101110111011100;
    hdldct_FixPt_t_2_1[182] = 16'sb1110000011100110;
    hdldct_FixPt_t_2_1[183] = 16'sb1110001111110100;
    hdldct_FixPt_t_2_1[184] = 16'sb1110011100000111;
    hdldct_FixPt_t_2_1[185] = 16'sb1110101000011110;
    hdldct_FixPt_t_2_1[186] = 16'sb1110110100111000;
    hdldct_FixPt_t_2_1[187] = 16'sb1111000001010101;
    hdldct_FixPt_t_2_1[188] = 16'sb1111001101110100;
    hdldct_FixPt_t_2_1[189] = 16'sb1111011010010101;
    hdldct_FixPt_t_2_1[190] = 16'sb1111100110111000;
    hdldct_FixPt_t_2_1[191] = 16'sb1111110011011100;
    hdldct_FixPt_t_2_1[192] = 16'sb0000000000000000;
    hdldct_FixPt_t_2_1[193] = 16'sb0000001100100100;
    hdldct_FixPt_t_2_1[194] = 16'sb0000011001001000;
    hdldct_FixPt_t_2_1[195] = 16'sb0000100101101011;
    hdldct_FixPt_t_2_1[196] = 16'sb0000110010001100;
    hdldct_FixPt_t_2_1[197] = 16'sb0000111110101011;
    hdldct_FixPt_t_2_1[198] = 16'sb0001001011001000;
    hdldct_FixPt_t_2_1[199] = 16'sb0001010111100010;
    hdldct_FixPt_t_2_1[200] = 16'sb0001100011111001;
    hdldct_FixPt_t_2_1[201] = 16'sb0001110000001100;
    hdldct_FixPt_t_2_1[202] = 16'sb0001111100011010;
    hdldct_FixPt_t_2_1[203] = 16'sb0010001000100100;
    hdldct_FixPt_t_2_1[204] = 16'sb0010010100101000;
    hdldct_FixPt_t_2_1[205] = 16'sb0010100000100111;
    hdldct_FixPt_t_2_1[206] = 16'sb0010101100011111;
    hdldct_FixPt_t_2_1[207] = 16'sb0010111000010001;
    hdldct_FixPt_t_2_1[208] = 16'sb0011000011111100;
    hdldct_FixPt_t_2_1[209] = 16'sb0011001111011111;
    hdldct_FixPt_t_2_1[210] = 16'sb0011011010111010;
    hdldct_FixPt_t_2_1[211] = 16'sb0011100110001101;
    hdldct_FixPt_t_2_1[212] = 16'sb0011110001010111;
    hdldct_FixPt_t_2_1[213] = 16'sb0011111100010111;
    hdldct_FixPt_t_2_1[214] = 16'sb0100000111001110;
    hdldct_FixPt_t_2_1[215] = 16'sb0100010001111011;
    hdldct_FixPt_t_2_1[216] = 16'sb0100011100011101;
    hdldct_FixPt_t_2_1[217] = 16'sb0100100110110100;
    hdldct_FixPt_t_2_1[218] = 16'sb0100110001000000;
    hdldct_FixPt_t_2_1[219] = 16'sb0100111011000000;
    hdldct_FixPt_t_2_1[220] = 16'sb0101000100110100;
    hdldct_FixPt_t_2_1[221] = 16'sb0101001110011011;
    hdldct_FixPt_t_2_1[222] = 16'sb0101010111110110;
    hdldct_FixPt_t_2_1[223] = 16'sb0101100001000011;
    hdldct_FixPt_t_2_1[224] = 16'sb0101101010000010;
    hdldct_FixPt_t_2_1[225] = 16'sb0101110010110100;
    hdldct_FixPt_t_2_1[226] = 16'sb0101111011010111;
    hdldct_FixPt_t_2_1[227] = 16'sb0110000011101100;
    hdldct_FixPt_t_2_1[228] = 16'sb0110001011110010;
    hdldct_FixPt_t_2_1[229] = 16'sb0110010011101001;
    hdldct_FixPt_t_2_1[230] = 16'sb0110011011010000;
    hdldct_FixPt_t_2_1[231] = 16'sb0110100010100111;
    hdldct_FixPt_t_2_1[232] = 16'sb0110101001101110;
    hdldct_FixPt_t_2_1[233] = 16'sb0110110000100100;
    hdldct_FixPt_t_2_1[234] = 16'sb0110110111001010;
    hdldct_FixPt_t_2_1[235] = 16'sb0110111101011111;
    hdldct_FixPt_t_2_1[236] = 16'sb0111000011100011;
    hdldct_FixPt_t_2_1[237] = 16'sb0111001001010101;
    hdldct_FixPt_t_2_1[238] = 16'sb0111001110110110;
    hdldct_FixPt_t_2_1[239] = 16'sb0111010100000101;
    hdldct_FixPt_t_2_1[240] = 16'sb0111011001000010;
    hdldct_FixPt_t_2_1[241] = 16'sb0111011101101100;
    hdldct_FixPt_t_2_1[242] = 16'sb0111100010000101;
    hdldct_FixPt_t_2_1[243] = 16'sb0111100110001010;
    hdldct_FixPt_t_2_1[244] = 16'sb0111101001111101;
    hdldct_FixPt_t_2_1[245] = 16'sb0111101101011101;
    hdldct_FixPt_t_2_1[246] = 16'sb0111110000101010;
    hdldct_FixPt_t_2_1[247] = 16'sb0111110011100100;
    hdldct_FixPt_t_2_1[248] = 16'sb0111110110001010;
    hdldct_FixPt_t_2_1[249] = 16'sb0111111000011110;
    hdldct_FixPt_t_2_1[250] = 16'sb0111111010011101;
    hdldct_FixPt_t_2_1[251] = 16'sb0111111100001010;
    hdldct_FixPt_t_2_1[252] = 16'sb0111111101100010;
    hdldct_FixPt_t_2_1[253] = 16'sb0111111110100111;
    hdldct_FixPt_t_2_1[254] = 16'sb0111111111011001;
    hdldct_FixPt_t_2_1[255] = 16'sb0111111111110110;
    //spssa
    //'hdldct_FixPt:35' c = fi( c1, numerictype( c1 ), fimath( a ) );
    //'hdldct_FixPt:34' c1 = divide( divideType( a1, b1 ), a1, b1 );
    //'hdldct_FixPt:33' b1 = fi( b, 'RoundMode', 'fix' );
    //'hdldct_FixPt:32' a1 = fi( a, 'RoundMode', 'fix' );
    //'hdldct_FixPt:31' if isfi( a ) && isfi( b )
    //'hdldct_FixPt:30' coder.inline( 'always' );
    //'hdldct_FixPt:14' d = fi(round( sqrt( fi_div_by_shift(1, 1) )*sqrt( fi_div(fi(2, 0, 2, 0), n) )*cos( t3 )*m ), 1, 8, 0, fm);
    //'hdldct_FixPt:16' d = fi(round( sqrt( fi_div_by_shift(2, 2) )*cos( t3 )*m ), 1, 8, 0, fm);
    //'hdldct_FixPt:15' else

    for(hdldct_FixPt_t_0_1 = 0; hdldct_FixPt_t_0_1 <= 255; hdldct_FixPt_t_0_1 = hdldct_FixPt_t_0_1 + 1) begin
      hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_t_0_1] = hdldct_FixPt_t_2_1[hdldct_FixPt_t_0_1];
    end

    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //'hdldct_FixPt:9' fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128);
    //'hdldct_FixPt:10' t1 = fi(pi*(i - fi(1, 0, 1, 0)), 0, 14, 10, fm);
    //'hdldct_FixPt:11' t2 = fi(fi_div((fi(2, 0, 2, 0)*j - fi(1, 0, 1, 0)), (fi(2, 0, 2, 0)*n)), 0, 14, 14, fm);
    //'hdldct_FixPt:30' coder.inline( 'always' );
    //'hdldct_FixPt:31' if isfi( a ) && isfi( b )
    //'hdldct_FixPt:32' a1 = fi( a, 'RoundMode', 'fix' );
    //'hdldct_FixPt:33' b1 = fi( b, 'RoundMode', 'fix' );
    //'hdldct_FixPt:34' c1 = divide( divideType( a1, b1 ), a1, b1 );
    //'hdldct_FixPt:35' c = fi( c1, numerictype( c1 ), fimath( a ) );
    //'hdldct_FixPt:12' t3 = fi(t1*t2, 0, 14, 10, fm);
    hdldct_FixPt_cast_39 = {n, 1'b0};
    hdldct_FixPt_sub_cast_14 = {j, 1'b0};
    hdldct_FixPt_sub_temp_9 = $signed({1'b0, hdldct_FixPt_sub_cast_14}) - 1;
    if (hdldct_FixPt_sub_temp_9[6] == 1'b1) begin
      hdldct_FixPt_cast_0_1 = 6'b000000;
    end
    else begin
      hdldct_FixPt_cast_0_1 = hdldct_FixPt_sub_temp_9[5:0];
    end
    hdldct_FixPt_cast_1_1 = {hdldct_FixPt_cast_0_1, 5'b00000};
    hdldct_FixPt_cast_2_1 = {n, 1'b0};
    if (hdldct_FixPt_cast_39 == 31'sd0) begin
      hdldct_FixPt_div_temp_3 = 11'b11111111111;
    end
    else begin
      hdldct_FixPt_div_temp_3 = hdldct_FixPt_cast_1_1 / hdldct_FixPt_cast_2_1;
    end
    hdldct_FixPt_sub_temp_0_1 = i - 1;
    hdldct_FixPt_mul_temp_18 = 13 * hdldct_FixPt_sub_temp_0_1;
    hdldct_FixPt_cast_3_1 = {hdldct_FixPt_mul_temp_18[5:0], 8'b00000000};
    hdldct_FixPt_cast_4_1 = {hdldct_FixPt_div_temp_3[4:0], 9'b000000000};
    hdldct_FixPt_mul_temp_0_1 = hdldct_FixPt_cast_3_1 * hdldct_FixPt_cast_4_1;
    hdldct_FixPt_t3_1 = hdldct_FixPt_mul_temp_0_1[27:14];
    hdldct_FixPt_inputValue_1 = hdldct_FixPt_t3_1;
    hdldct_FixPt_cast_5_1 = {hdldct_FixPt_inputValue_1, 16'b0000000000000000};
    hdldct_FixPt_iA_1 = hdldct_FixPt_cast_5_1;
    hdldct_FixPt_inputValue_0_1 = hdldct_FixPt_t3_1;
    hdldct_FixPt_cast_6_1 = {hdldct_FixPt_inputValue_0_1, 16'b0000000000000000};
    hdldct_FixPt_iA_0_1 = hdldct_FixPt_cast_6_1;
    //'hdldct_FixPt:13' if i==1
    if (i == 3'b001) begin
      if (n == 31'sd0) begin
        hdldct_FixPt_div_temp_0_1 = 4'b1111;
      end
      else begin
        hdldct_FixPt_div_temp_0_1 = 8 / n;
      end
      hdldct_FixPt_c1_1 = hdldct_FixPt_div_temp_0_1;
      hdldct_FixPt_y_1 = 3'b000;

      for(hdldct_FixPt_i_1 = 2; hdldct_FixPt_i_1 >= 0; hdldct_FixPt_i_1 = hdldct_FixPt_i_1 -1) begin
        hdldct_FixPt_cast_9_1[hdldct_FixPt_i_1] = hdldct_FixPt_i_1[7:0];
        hdldct_FixPt_sll_temp_1[hdldct_FixPt_i_1] = 1 <<< hdldct_FixPt_cast_9_1[hdldct_FixPt_i_1];
        hdldct_FixPt_ytemp_1 = hdldct_FixPt_y_1 | hdldct_FixPt_sll_temp_1[hdldct_FixPt_i_1];
        hdldct_FixPt_mul_temp_5_1[hdldct_FixPt_i_1] = hdldct_FixPt_ytemp_1 * hdldct_FixPt_ytemp_1;
        hdldct_FixPt_cast_14_1[hdldct_FixPt_i_1] = hdldct_FixPt_c1_1;
        if (hdldct_FixPt_mul_temp_5_1[hdldct_FixPt_i_1] <= hdldct_FixPt_cast_14_1[hdldct_FixPt_i_1]) begin
          hdldct_FixPt_y_1 = hdldct_FixPt_ytemp_1;
        end
      end

      hdldct_FixPt_add_cast_12 = hdldct_FixPt_y_1;
      hdldct_FixPt_add_temp_8 = hdldct_FixPt_add_cast_12 + 1;
      if (hdldct_FixPt_add_temp_8[3] != 1'b0) begin
        hdldct_FixPt_ytempPlusLsb_1 = 3'b111;
      end
      else begin
        hdldct_FixPt_ytempPlusLsb_1 = hdldct_FixPt_add_temp_8[2:0];
      end
      hdldct_FixPt_mul_temp_3_1 = hdldct_FixPt_ytempPlusLsb_1 * hdldct_FixPt_ytempPlusLsb_1;
      hdldct_FixPt_sub_cast_3_1 = hdldct_FixPt_mul_temp_3_1;
      hdldct_FixPt_sub_cast_4_1 = hdldct_FixPt_c1_1;
      hdldct_FixPt_sub_temp_3_1 = hdldct_FixPt_sub_cast_3_1 - hdldct_FixPt_sub_cast_4_1;
      if (hdldct_FixPt_sub_temp_3_1[6] == 1'b1) begin
        hdldct_FixPt_cast_12_1 = 6'b000000;
      end
      else begin
        hdldct_FixPt_cast_12_1 = hdldct_FixPt_sub_temp_3_1[5:0];
      end
      hdldct_FixPt_sub_cast_5_1 = hdldct_FixPt_c1_1;
      hdldct_FixPt_mul_temp_4_1 = hdldct_FixPt_y_1 * hdldct_FixPt_y_1;
      hdldct_FixPt_sub_cast_6_1 = hdldct_FixPt_mul_temp_4_1;
      hdldct_FixPt_sub_temp_4_1 = hdldct_FixPt_sub_cast_5_1 - hdldct_FixPt_sub_cast_6_1;
      if (hdldct_FixPt_sub_temp_4_1[6] == 1'b1) begin
        hdldct_FixPt_cast_13_1 = 6'b000000;
      end
      else begin
        hdldct_FixPt_cast_13_1 = hdldct_FixPt_sub_temp_4_1[5:0];
      end
      if (hdldct_FixPt_cast_12_1 < hdldct_FixPt_cast_13_1) begin
      end
      else begin
        hdldct_FixPt_ytempPlusLsb_1 = hdldct_FixPt_y_1;
      end
      if (hdldct_FixPt_y_1 < 3'b111) begin
        hdldct_FixPt_y_1 = hdldct_FixPt_ytempPlusLsb_1;
      end
      if (hdldct_FixPt_c1_1 <= 5'b00000) begin
        hdldct_FixPt_y_1 = 3'b000;
      end
      if ((hdldct_FixPt_inputValue_1 > 16'b0001100100100010) || (hdldct_FixPt_inputValue_1 < 16'b0000000000000000)) begin
        hdldct_FixPt_div_temp_2_1 = hdldct_FixPt_iA_1 / 421657428;
        hdldct_FixPt_sub_cast_9_1 = hdldct_FixPt_div_temp_2_1 * 421657428;
        hdldct_FixPt_sub_temp_6_1 = hdldct_FixPt_iA_1 - hdldct_FixPt_sub_cast_9_1;
        hdldct_FixPt_tmp_1_1 = hdldct_FixPt_sub_temp_6_1[28:13];
      end
      else begin
        hdldct_FixPt_tmp_1_1 = {hdldct_FixPt_inputValue_1[12:0], 3'b000};
      end
      hdldct_FixPt_cast_23_1 = hdldct_FixPt_tmp_1_1;
      hdldct_FixPt_mul_temp_10_1 = 32'b10100010111110010110010100100100 * hdldct_FixPt_cast_23_1;
      hdldct_FixPt_cast_24_1 = hdldct_FixPt_mul_temp_10_1[46:15];
      hdldct_FixPt_fullScaleIndex_0_1 = hdldct_FixPt_cast_24_1[31:16];
      hdldct_FixPt_idxLUTLoZero_0_1 = hdldct_FixPt_fullScaleIndex_0_1[15:8];
      hdldct_FixPt_idxLUTLoAddr_0_1 = $signed({1'b0, hdldct_FixPt_idxLUTLoZero_0_1}) + 1;
      hdldct_FixPt_cast_25_1 = hdldct_FixPt_fullScaleIndex_0_1[7:0];
      hdldct_FixPt_add_temp_4_1 = $signed({1'b0, hdldct_FixPt_idxLUTLoZero_0_1 + 8'b00000001}) + 1;
      hdldct_FixPt_sub_cast_10_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_add_temp_4_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_add_temp_4_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_sub_cast_11_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_0_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_0_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_sub_temp_7_1 = hdldct_FixPt_sub_cast_10_1 - hdldct_FixPt_sub_cast_11_1;
      hdldct_FixPt_mul_temp_11_1 = hdldct_FixPt_cast_25_1 * hdldct_FixPt_sub_temp_7_1;
      hdldct_FixPt_cast_26_1 = hdldct_FixPt_mul_temp_11_1[39:8];
      hdldct_FixPt_temp_0_1 = hdldct_FixPt_cast_26_1[30:15];
      hdldct_FixPt_mul_temp_12_1 = 6 * hdldct_FixPt_y_1;
      hdldct_FixPt_cast_27_1 = hdldct_FixPt_mul_temp_12_1;
      hdldct_FixPt_add_cast_6_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_0_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_0_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_add_cast_7_1 = {hdldct_FixPt_temp_0_1[15], {hdldct_FixPt_temp_0_1, 15'b000000000000000}};
      hdldct_FixPt_add_temp_5_1 = hdldct_FixPt_add_cast_6_1 + hdldct_FixPt_add_cast_7_1;
      hdldct_FixPt_cast_28_1 = hdldct_FixPt_add_temp_5_1[30:15];
      hdldct_FixPt_mul_temp_13_1 = hdldct_FixPt_cast_27_1 * hdldct_FixPt_cast_28_1;
      if ((hdldct_FixPt_mul_temp_13_1[22] == 1'b0) && (hdldct_FixPt_mul_temp_13_1[21] != 1'b0)) begin
        hdldct_FixPt_cast_29_1 = 22'sb0111111111111111111111;
      end
      else if ((hdldct_FixPt_mul_temp_13_1[22] == 1'b1) && (hdldct_FixPt_mul_temp_13_1[21] != 1'b1)) begin
        hdldct_FixPt_cast_29_1 = 22'sb1000000000000000000000;
      end
      else begin
        hdldct_FixPt_cast_29_1 = hdldct_FixPt_mul_temp_13_1[21:0];
      end
      hdldct_FixPt_cast_30_1 = m;
      hdldct_FixPt_mul_temp_14_1 = hdldct_FixPt_cast_29_1 * hdldct_FixPt_cast_30_1;
      if ((hdldct_FixPt_mul_temp_14_1[30] == 1'b0) && (hdldct_FixPt_mul_temp_14_1[29] != 1'b0)) begin
        hdldct_FixPt_c_0_1 = 30'sb011111111111111111111111111111;
      end
      else if ((hdldct_FixPt_mul_temp_14_1[30] == 1'b1) && (hdldct_FixPt_mul_temp_14_1[29] != 1'b1)) begin
        hdldct_FixPt_c_0_1 = 30'sb100000000000000000000000000000;
      end
      else begin
        hdldct_FixPt_c_0_1 = hdldct_FixPt_mul_temp_14_1[29:0];
      end
      hdldct_FixPt_mul_temp_15_1 = 6 * hdldct_FixPt_y_1;
      hdldct_FixPt_cast_31_1 = hdldct_FixPt_mul_temp_15_1;
      hdldct_FixPt_add_cast_8_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_0_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_0_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_add_cast_9_1 = {hdldct_FixPt_temp_0_1[15], {hdldct_FixPt_temp_0_1, 15'b000000000000000}};
      hdldct_FixPt_add_temp_6_1 = hdldct_FixPt_add_cast_8_1 + hdldct_FixPt_add_cast_9_1;
      hdldct_FixPt_cast_32_1 = hdldct_FixPt_add_temp_6_1[30:15];
      hdldct_FixPt_mul_temp_16_1 = hdldct_FixPt_cast_31_1 * hdldct_FixPt_cast_32_1;
      if ((hdldct_FixPt_mul_temp_16_1[22] == 1'b0) && (hdldct_FixPt_mul_temp_16_1[21] != 1'b0)) begin
        hdldct_FixPt_cast_33_1 = 22'sb0111111111111111111111;
      end
      else if ((hdldct_FixPt_mul_temp_16_1[22] == 1'b1) && (hdldct_FixPt_mul_temp_16_1[21] != 1'b1)) begin
        hdldct_FixPt_cast_33_1 = 22'sb1000000000000000000000;
      end
      else begin
        hdldct_FixPt_cast_33_1 = hdldct_FixPt_mul_temp_16_1[21:0];
      end
      hdldct_FixPt_cast_34_1 = m;
      hdldct_FixPt_mul_temp_17_1 = hdldct_FixPt_cast_33_1 * hdldct_FixPt_cast_34_1;
      if ((hdldct_FixPt_mul_temp_17_1[30] == 1'b0) && (hdldct_FixPt_mul_temp_17_1[29] != 1'b0)) begin
        hdldct_FixPt_cast_35_1 = 30'sb011111111111111111111111111111;
      end
      else if ((hdldct_FixPt_mul_temp_17_1[30] == 1'b1) && (hdldct_FixPt_mul_temp_17_1[29] != 1'b1)) begin
        hdldct_FixPt_cast_35_1 = 30'sb100000000000000000000000000000;
      end
      else begin
        hdldct_FixPt_cast_35_1 = hdldct_FixPt_mul_temp_17_1[29:0];
      end
      if (hdldct_FixPt_cast_35_1 < 30'sb000000000000000000000000000000) begin
        hdldct_FixPt_sub_cast_12_1 = ({hdldct_FixPt_c_0_1[29], hdldct_FixPt_c_0_1[29:18]}) + $signed({1'b0, (|hdldct_FixPt_c_0_1[17:0])});
        hdldct_FixPt_sub_cast_13_1 = hdldct_FixPt_sub_cast_12_1;
        hdldct_FixPt_sub_temp_8_1 = hdldct_FixPt_sub_cast_13_1 - 1;
        if ((hdldct_FixPt_sub_temp_8_1[13] == 1'b0) && (hdldct_FixPt_sub_temp_8_1[12] != 1'b0)) begin
          hdldct_FixPt_cast_37_1 = 13'sb0111111111111;
        end
        else if ((hdldct_FixPt_sub_temp_8_1[13] == 1'b1) && (hdldct_FixPt_sub_temp_8_1[12] != 1'b1)) begin
          hdldct_FixPt_cast_37_1 = 13'sb1000000000000;
        end
        else begin
          hdldct_FixPt_cast_37_1 = hdldct_FixPt_sub_temp_8_1[12:0];
        end
        hdldct_FixPt_cast_38_1 = ({hdldct_FixPt_cast_37_1[12], hdldct_FixPt_cast_37_1[12:1]}) + $signed({1'b0, hdldct_FixPt_cast_37_1[0]});
        if ((hdldct_FixPt_cast_38_1[12] == 1'b0) && (hdldct_FixPt_cast_38_1[11] != 1'b0)) begin
          hdldct_FixPt_tmp_2_1 = 12'sb011111111111;
        end
        else if ((hdldct_FixPt_cast_38_1[12] == 1'b1) && (hdldct_FixPt_cast_38_1[11] != 1'b1)) begin
          hdldct_FixPt_tmp_2_1 = 12'sb100000000000;
        end
        else begin
          hdldct_FixPt_tmp_2_1 = hdldct_FixPt_cast_38_1[11:0];
        end
      end
      else begin
        hdldct_FixPt_add_cast_10_1 = {hdldct_FixPt_c_0_1[29], hdldct_FixPt_c_0_1[29:18]};
        hdldct_FixPt_add_cast_11_1 = hdldct_FixPt_add_cast_10_1;
        hdldct_FixPt_add_temp_7_1 = hdldct_FixPt_add_cast_11_1 + 1;
        if ((hdldct_FixPt_add_temp_7_1[13] == 1'b0) && (hdldct_FixPt_add_temp_7_1[12] != 1'b0)) begin
          hdldct_FixPt_cast_36_1 = 13'sb0111111111111;
        end
        else if ((hdldct_FixPt_add_temp_7_1[13] == 1'b1) && (hdldct_FixPt_add_temp_7_1[12] != 1'b1)) begin
          hdldct_FixPt_cast_36_1 = 13'sb1000000000000;
        end
        else begin
          hdldct_FixPt_cast_36_1 = hdldct_FixPt_add_temp_7_1[12:0];
        end
        if ((hdldct_FixPt_cast_36_1[12] == 1'b0) && (hdldct_FixPt_cast_36_1[11:1] == 11'b11111111111)) begin
          hdldct_FixPt_tmp_2_1 = 12'sb011111111111;
        end
        else begin
          hdldct_FixPt_tmp_2_1 = hdldct_FixPt_cast_36_1[12:1];
        end
      end
      d_1 = hdldct_FixPt_tmp_2_1[7:0];
    end
    else begin
      if ((hdldct_FixPt_inputValue_0_1 > 16'b0001100100100010) || (hdldct_FixPt_inputValue_0_1 < 16'b0000000000000000)) begin
        hdldct_FixPt_div_temp_1_1 = hdldct_FixPt_iA_0_1 / 421657428;
        hdldct_FixPt_sub_cast_0_1 = hdldct_FixPt_div_temp_1_1 * 421657428;
        hdldct_FixPt_sub_temp_1_1 = hdldct_FixPt_iA_0_1 - hdldct_FixPt_sub_cast_0_1;
        hdldct_FixPt_tmp_3 = hdldct_FixPt_sub_temp_1_1[28:13];
      end
      else begin
        hdldct_FixPt_tmp_3 = {hdldct_FixPt_inputValue_0_1[12:0], 3'b000};
      end
      hdldct_FixPt_cast_7_1 = hdldct_FixPt_tmp_3;
      hdldct_FixPt_mul_temp_1_1 = 32'b10100010111110010110010100100100 * hdldct_FixPt_cast_7_1;
      hdldct_FixPt_cast_8_1 = hdldct_FixPt_mul_temp_1_1[46:15];
      hdldct_FixPt_fullScaleIndex_1 = hdldct_FixPt_cast_8_1[31:16];
      hdldct_FixPt_idxLUTLoZero_1 = hdldct_FixPt_fullScaleIndex_1[15:8];
      hdldct_FixPt_idxLUTLoAddr_1 = $signed({1'b0, hdldct_FixPt_idxLUTLoZero_1}) + 1;
      hdldct_FixPt_cast_10_1 = hdldct_FixPt_fullScaleIndex_1[7:0];
      hdldct_FixPt_add_temp_0_1 = $signed({1'b0, hdldct_FixPt_idxLUTLoZero_1 + 8'b00000001}) + 1;
      hdldct_FixPt_sub_cast_1_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_add_temp_0_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_add_temp_0_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_sub_cast_2_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_sub_temp_2_1 = hdldct_FixPt_sub_cast_1_1 - hdldct_FixPt_sub_cast_2_1;
      hdldct_FixPt_mul_temp_2_1 = hdldct_FixPt_cast_10_1 * hdldct_FixPt_sub_temp_2_1;
      hdldct_FixPt_cast_11_1 = hdldct_FixPt_mul_temp_2_1[39:8];
      hdldct_FixPt_temp_1 = hdldct_FixPt_cast_11_1[30:15];
      hdldct_FixPt_add_cast_0_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_add_cast_1_1 = {hdldct_FixPt_temp_1[15], {hdldct_FixPt_temp_1, 15'b000000000000000}};
      hdldct_FixPt_add_temp_1_1 = hdldct_FixPt_add_cast_0_1 + hdldct_FixPt_add_cast_1_1;
      hdldct_FixPt_cast_15_1 = hdldct_FixPt_add_temp_1_1[30:15];
      hdldct_FixPt_mul_temp_6_1 = 23170 * hdldct_FixPt_cast_15_1;
      hdldct_FixPt_cast_16_1 = m;
      hdldct_FixPt_mul_temp_7_1 = hdldct_FixPt_mul_temp_6_1 * hdldct_FixPt_cast_16_1;
      if ((hdldct_FixPt_mul_temp_7_1[40] == 1'b0) && (hdldct_FixPt_mul_temp_7_1[39] != 1'b0)) begin
        hdldct_FixPt_c_1 = 40'sh7FFFFFFFFF;
      end
      else if ((hdldct_FixPt_mul_temp_7_1[40] == 1'b1) && (hdldct_FixPt_mul_temp_7_1[39] != 1'b1)) begin
        hdldct_FixPt_c_1 = 40'sh8000000000;
      end
      else begin
        hdldct_FixPt_c_1 = hdldct_FixPt_mul_temp_7_1[39:0];
      end
      hdldct_FixPt_add_cast_2_1 = {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_1 - 1][15], {hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_idxLUTLoAddr_1 - 1], 15'b000000000000000}};
      hdldct_FixPt_add_cast_3_1 = {hdldct_FixPt_temp_1[15], {hdldct_FixPt_temp_1, 15'b000000000000000}};
      hdldct_FixPt_add_temp_2_1 = hdldct_FixPt_add_cast_2_1 + hdldct_FixPt_add_cast_3_1;
      hdldct_FixPt_cast_17_1 = hdldct_FixPt_add_temp_2_1[30:15];
      hdldct_FixPt_mul_temp_8_1 = 23170 * hdldct_FixPt_cast_17_1;
      hdldct_FixPt_cast_18_1 = m;
      hdldct_FixPt_mul_temp_9_1 = hdldct_FixPt_mul_temp_8_1 * hdldct_FixPt_cast_18_1;
      if ((hdldct_FixPt_mul_temp_9_1[40] == 1'b0) && (hdldct_FixPt_mul_temp_9_1[39] != 1'b0)) begin
        hdldct_FixPt_cast_19_1 = 40'sh7FFFFFFFFF;
      end
      else if ((hdldct_FixPt_mul_temp_9_1[40] == 1'b1) && (hdldct_FixPt_mul_temp_9_1[39] != 1'b1)) begin
        hdldct_FixPt_cast_19_1 = 40'sh8000000000;
      end
      else begin
        hdldct_FixPt_cast_19_1 = hdldct_FixPt_mul_temp_9_1[39:0];
      end
      if (hdldct_FixPt_cast_19_1 < 40'sh0000000000) begin
        hdldct_FixPt_sub_cast_7_1 = ({hdldct_FixPt_c_1[39], hdldct_FixPt_c_1[39:29]}) + $signed({1'b0, (|hdldct_FixPt_c_1[28:0])});
        hdldct_FixPt_sub_cast_8_1 = hdldct_FixPt_sub_cast_7_1;
        hdldct_FixPt_sub_temp_5_1 = hdldct_FixPt_sub_cast_8_1 - 1;
        if ((hdldct_FixPt_sub_temp_5_1[12] == 1'b0) && (hdldct_FixPt_sub_temp_5_1[11] != 1'b0)) begin
          hdldct_FixPt_cast_21_1 = 12'sb011111111111;
        end
        else if ((hdldct_FixPt_sub_temp_5_1[12] == 1'b1) && (hdldct_FixPt_sub_temp_5_1[11] != 1'b1)) begin
          hdldct_FixPt_cast_21_1 = 12'sb100000000000;
        end
        else begin
          hdldct_FixPt_cast_21_1 = hdldct_FixPt_sub_temp_5_1[11:0];
        end
        hdldct_FixPt_cast_22_1 = ({hdldct_FixPt_cast_21_1[11], hdldct_FixPt_cast_21_1[11:1]}) + $signed({1'b0, hdldct_FixPt_cast_21_1[0]});
        if ((hdldct_FixPt_cast_22_1[11] == 1'b0) && (hdldct_FixPt_cast_22_1[10] != 1'b0)) begin
          hdldct_FixPt_tmp_0_1 = 11'sb01111111111;
        end
        else if ((hdldct_FixPt_cast_22_1[11] == 1'b1) && (hdldct_FixPt_cast_22_1[10] != 1'b1)) begin
          hdldct_FixPt_tmp_0_1 = 11'sb10000000000;
        end
        else begin
          hdldct_FixPt_tmp_0_1 = hdldct_FixPt_cast_22_1[10:0];
        end
      end
      else begin
        hdldct_FixPt_add_cast_4_1 = {hdldct_FixPt_c_1[39], hdldct_FixPt_c_1[39:29]};
        hdldct_FixPt_add_cast_5_1 = hdldct_FixPt_add_cast_4_1;
        hdldct_FixPt_add_temp_3_1 = hdldct_FixPt_add_cast_5_1 + 1;
        if ((hdldct_FixPt_add_temp_3_1[12] == 1'b0) && (hdldct_FixPt_add_temp_3_1[11] != 1'b0)) begin
          hdldct_FixPt_cast_20_1 = 12'sb011111111111;
        end
        else if ((hdldct_FixPt_add_temp_3_1[12] == 1'b1) && (hdldct_FixPt_add_temp_3_1[11] != 1'b1)) begin
          hdldct_FixPt_cast_20_1 = 12'sb100000000000;
        end
        else begin
          hdldct_FixPt_cast_20_1 = hdldct_FixPt_add_temp_3_1[11:0];
        end
        if ((hdldct_FixPt_cast_20_1[11] == 1'b0) && (hdldct_FixPt_cast_20_1[10:1] == 10'b1111111111)) begin
          hdldct_FixPt_tmp_0_1 = 11'sb01111111111;
        end
        else begin
          hdldct_FixPt_tmp_0_1 = hdldct_FixPt_cast_20_1[11:1];
        end
      end
      d_1 = hdldct_FixPt_tmp_0_1[7:0];
    end

    for(hdldct_FixPt_t_1_1 = 0; hdldct_FixPt_t_1_1 <= 255; hdldct_FixPt_t_1_1 = hdldct_FixPt_t_1_1 + 1) begin
      hdldct_FixPt_FI_SIN_COS_LUT_1[hdldct_FixPt_t_1_1] = hdldct_FixPt_FI_SIN_COS_LUT_2[hdldct_FixPt_t_1_1];
    end

  end



  assign ce_out = clk_enable;

  assign d = d_1;

endmodule  // hdldct_FixPt

